# Generated by Django 4.2.4 on 2023-09-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.CharField(max_length=255)),
                ('Question2', models.CharField(max_length=255)),
                ('Question3', models.CharField(max_length=255)),
                ('Question4', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
