# Generated by Django 4.2.4 on 2023-09-28 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_quiz_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='response',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
