# Generated by Django 4.2.4 on 2023-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_choice_quiztaker_remove_questionattempt_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='quiz_score',
            field=models.FloatField(default=0),
        ),
    ]
