# Generated by Django 4.2.4 on 2023-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiztaker_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
