# Generated by Django 4.2.4 on 2023-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
