# Generated by Django 4.2.4 on 2023-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_quiztaker_attempts_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
    ]
