# Generated by Django 4.2.4 on 2023-09-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_teacheraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAccount',
        ),
    ]
