# Generated by Django 4.2.4 on 2023-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_teacheraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
