# Generated by Django 4.2.4 on 2023-09-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='grade',
            new_name='quiz_score',
        ),
    ]
