# Generated by Django 4.2.4 on 2023-10-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_grade_account_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='quiz_score',
        ),
    ]
