# Generated by Django 4.2.4 on 2023-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
