# Generated by Django 4.2.4 on 2023-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_grade_perc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='perc',
        ),
        migrations.AddField(
            model_name='grade',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
