# Generated by Django 4.2.4 on 2023-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_weights_crit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit',
            name='crit',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
