# Generated by Django 4.2.4 on 2023-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_crit_crit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weights',
            name='crit',
            field=models.CharField(default='N', max_length=100),
        ),
        migrations.DeleteModel(
            name='Crit',
        ),
    ]
